package com.yjmedia.adkan.mapper.generator;

import com.yjmedia.adkan.model.generator.Bunryu1Tbl;
import com.yjmedia.adkan.model.generator.Bunryu1TblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Bunryu1TblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUNRYU1_TBL
     *
     * @mbggenerated Sun May 08 18:39:47 KST 2016
     */
    int countByExample(Bunryu1TblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUNRYU1_TBL
     *
     * @mbggenerated Sun May 08 18:39:47 KST 2016
     */
    int deleteByExample(Bunryu1TblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUNRYU1_TBL
     *
     * @mbggenerated Sun May 08 18:39:47 KST 2016
     */
    int insert(Bunryu1Tbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUNRYU1_TBL
     *
     * @mbggenerated Sun May 08 18:39:47 KST 2016
     */
    int insertSelective(Bunryu1Tbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUNRYU1_TBL
     *
     * @mbggenerated Sun May 08 18:39:47 KST 2016
     */
    List<Bunryu1Tbl> selectByExample(Bunryu1TblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUNRYU1_TBL
     *
     * @mbggenerated Sun May 08 18:39:47 KST 2016
     */
    int updateByExampleSelective(@Param("record") Bunryu1Tbl record, @Param("example") Bunryu1TblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUNRYU1_TBL
     *
     * @mbggenerated Sun May 08 18:39:47 KST 2016
     */
    int updateByExample(@Param("record") Bunryu1Tbl record, @Param("example") Bunryu1TblExample example);
}